name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor app
        run: dotnet publish -c Release -o release

      - name: Copy site files
        run: |
          cp -r release/wwwroot ./wwwroot
          echo "blazor.bojangrujic2001.github.io" > ./wwwroot/CNAME || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
